{
 "title": "Openstack Status",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Openstack Servers amd64",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "openstack_nova_total_vms{agent=\"prod-snapd-env-92\"}",
     "legendFormat": "Number of VMs"
    }
   ]
  },
  {
   "title": "Openstack Storage Used amd64 (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(openstack_cinder_volume_gb{agent=\"prod-snapd-env-92\"})",
     "legendFormat": "GB used"
    }
   ]
  },
  {
   "title": "Openstack Servers arm64",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "openstack_nova_total_vms{agent=\"prod-snapd-env-93\"}",
     "legendFormat": "Number of VMs"
    }
   ]
  },
  {
   "title": "Openstack Storage Used arm64 (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(openstack_cinder_volume_gb{agent=\"prod-snapd-env-93\"})",
     "legendFormat": "GB used"
    }
   ]
  },
  {
   "title": "Openstack allocation issues",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time(\n    {project=\"snapd\"} |= \"Cannot allocate openstack:\" [1h]\n  )\n)",
     "legendFormat": "Cannot allocate"
    },
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time(\n    {project=\"snapd\"} |= \"Allocated openstack\" [1h]\n  )\n)",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Total allocated instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{project=\"snapd\"} |= `Allocated openstack:`"
    }
   ]
  },
  {
   "title": "Total errors allocating instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{project=\"snapd\"} |= `Cannot allocate openstack:`"
    }
   ]
  },
  {
   "title": "Openstack allocation details",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{project=\"snapd\"} |= `Cannot allocate openstack:`"
    }
   ]
  },
  {
   "title": "Openstack allocation errors by system",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{project=\"snapd\"} |= `Cannot allocate openstack:` | pattern `<_>openstack:<system>:<_>`"
    }
   ]
  },
  {
   "title": "Openstack Volumes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    { "expr": "openstack_cinder_volumes", "legendFormat": "Number of volumes" }
   ]
  }
 ]
}