name: general configuration for snaps

archive-time:
    Edge: 6d
    Beta: 2w
    Candidate: 2w
    Stable: 4w

archive-list: Complete

delete-time:
    Complete: 1w

snaps-auto-move:
  - core
  - core18
  - core20
  - core22
  - snapd
