name: testing snap workflow for core snap on beta channel
checklists:
    Sign-Off:
        - name: Clear for Landing
          default: true
        - name: Ready for Edge
          default: true
        - name: Ready for Beta
          default: true
        - name: Ready for Candidate
          default: false
        - name: Ready for Stable
          default: false
        - name: Can be Archived
          default: false
    Results:
        - name: pi2
          default: false
        - name: pi2-cconf
          default: false
        - name: pi3
          default: false
        - name: pi3-cconf
          default: false
        - name: dragonboard
          default: false
        - name: dragonboard-cconf
          default: false
        - name: pc-amd64
          default: false
        - name: pc-amd64-cconf
          default: false
    Executions:
        - name: pi2
          default: false
        - name: pi2-cconf
          default: false
        - name: pi3
          default: false
        - name: pi3-cconf
          default: false
        - name: dragonboard
          default: false
        - name: dragonboard-cconf
          default: false
        - name: pc-amd64
          default: false
        - name: pc-amd64-cconf
          default: false
complete:
    sign:
        sign-checklist: Sign-Off
        sign-actions:
            - source: Results
              target: Ready for Candidate
