    #this backend is used for edge validation
    testflinger:        
        halt-timeout: 15h
        wait-timeout: 2h
        warn-timeout: 5m
        kill-timeout: 14h
        systems:
            - ubuntu-core-16-rpi2:
                  queue: cert-rpi2
                  image: https://storage.googleapis.com/snapd-spread-tests/images/pi2-16-stable-core_beta/pi2.img.xz
                  workers: 1
                  username: ubuntu
                  password: ubuntu            
            - ubuntu-core-18-rpi2:
                  queue: cert-rpi2
                  image: https://storage.googleapis.com/snapd-spread-tests/images/pi2-18-stable-snapd_beta/pi.img.xz
                  workers: 1
                  username: ubuntu
                  password: ubuntu
            - ubuntu-core-16-dragonboard:
                  queue: dragonboard
                  image: https://storage.googleapis.com/snapd-spread-tests/images/dragonboard-16-stable-core_beta/dragonboard.img.xz
                  workers: 1
                  username: ubuntu
                  password: ubuntu            
            - ubuntu-core-18-dragonboard:
                  queue: dragonboard
                  image: https://storage.googleapis.com/snapd-spread-tests/images/dragonboard-18-stable-snapd_beta/dragonboard.img.xz
                  workers: 1
                  username: ubuntu
                  password: ubuntu
            - ubuntu-core-18-nuc:
                  queue: dawson-i-uc20-fde
                  image: https://storage.googleapis.com/snapd-spread-tests/images/pc-amd64-20-stable-snapd_beta/pc.img.xz
                  workers: 1
                  username: ubuntu
                  password: ubuntu
            - ubuntu-core-16-rpi3:
                  queue: rpi3b
                  image: https://storage.googleapis.com/snapd-spread-tests/images/pi3-16-stable-core_beta/pi3.img.xz
                  workers: 1
                  username: ubuntu
                  password: ubuntu            
            - ubuntu-core-18-rpi3:
                  queue: rpi3b
                  image: https://storage.googleapis.com/snapd-spread-tests/images/pi3-18-stable-snapd_beta/pi.img.xz
                  workers: 1
                  username: ubuntu
                  password: ubuntu
            - ubuntu-core-20-rpi3:
                  queue: rpi3b
                  image: https://storage.googleapis.com/snapd-spread-tests/images/pi3-20-stable-snapd_beta/pi.img.xz
                  workers: 1
                  username: ubuntu
                  password: ubuntu
            - ubuntu-core-22-rpi3:
                  queue: rpi3b
                  image: https://storage.googleapis.com/snapd-spread-tests/images/pi3-22-stable-snapd_beta/pi.img.xz
                  workers: 1
                  username: ubuntu
                  password: ubuntu
            - ubuntu-core-20-rpi4:
                  queue: rpi4b8g
                  image: https://storage.googleapis.com/snapd-spread-tests/images/pi4-20-stable-snapd_beta/pi.img.xz
                  workers: 1
                  username: ubuntu
                  password: ubuntu
            - ubuntu-core-22-rpi4:
                  queue: rpi4b8g
                  image: https://storage.googleapis.com/snapd-spread-tests/images/pi4-22-stable-snapd_beta/pi.img.xz
                  workers: 1
                  username: ubuntu
                  password: ubuntu
