#!/usr/bin/env python3

import os

from datetime import datetime
from launchpadlib.launchpad import Launchpad

# basic data
series = 'xenial'

# basic paths
workdir = os.getenv("SNAP_DATA")

# we need to store credentials once for cronned builds
cachedir = os.path.join(workdir, "cache")
creds = os.path.join(workdir, "credentials")

print('Starting builder execution')
print('Working dir: {}'.format(workdir))

# log in
launchpad = Launchpad.login_with('Ubuntu Core Builds',
                                 'production', cachedir,
                                 credentials_file=creds,
                                 version='devel')

# get snappy-dev team data and ppa
snappydev = launchpad.people['snappy-dev']
imageppa = snappydev.getPPAByName(name='edge')

# get snap
ubuntucore = launchpad.snaps.getByName(name='core',
                                       owner=snappydev)

# get distro info
ubuntu = launchpad.distributions['ubuntu']
release = ubuntu.getSeries(name_or_version=series)

# print a stamp
stamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
print("Trying to trigger builds at: {}".format(stamp))

# loop over arches and trigger builds
request = ubuntucore.requestBuilds(archive=imageppa,
                                   pocket='Updates')
buildid = str(request).rsplit('/', 1)[-1]
print("All architectures are building under: {} build".format(buildid))
