name: spread-docs
version: '1.0'
summary: Generate spread tests documentation from a github project
base: core22
confinement: strict
grade: stable

description: |
  This snap allows to generate documentation from a github repo
  which contains spread tests on it. The snap clones and update the
  github project and searches all the tests on it, then based on the
  tests found generates the output with tests the content.

apps:
    help:
        command: help

    git-project:
        command: git-project
        plugs: [network]

    search:
        command: search

parts:
  git:
      plugin: make
      source: .
      stage-packages:
          - curl
          - jq
          - libcurl4-openssl-dev
          - wget
      build-packages:
          - asciidoc
          - build-essential
          - curl
          - cvs
          - cvsps
          - docbook-xsl
          - gettext
          - libcurl4-openssl-dev
          - libdbd-sqlite3-perl
          - libsvn-perl
          - libyaml-perl
          - subversion
          - xmlto
          - wget
          - zlib1g-dev
      prime:
          - usr/
  doc:
      plugin: dump
      source: .
      stage-snaps:
        - yq
