name: git-cron
version: '1.1.1'
summary: Basic support for launching git-cron jobs
base: core20
confinement: strict
grade: stable

description: |
    This snap declares a simple daemon for checking the jobs
    defined in the defined project branches.

    For each of the jobs, the checker/run script is executed,
    it looks for changes on external resources, extracting the
    relevant information according to the trigger file. In case
    a change in the external resource related to a particular
    branch is detected, then a commit is pushed to that branch,
    so that the travis execution is triggered.

    The snap must be able to push to the defined repo,
    the credentials for doing so are passed to the snap via a
    configure hook

        $ snap set git-cron username=<username> password=<password>

    The project information is sent to the snap via a
    configure hook

        $ snap set git-cron project-url=<project_url> project-name=<project_name> jobs-dir=<jobs_dir>

apps:
    cron:
        command: bin/cron
        daemon: simple
        plugs: [network]
        passthrough:
            # Run every 15 minutes
            timer: 0:00-24:00/96

layout:
  /etc/wgetrc:
    bind-file: $SNAP_DATA/etc/wgetrc

parts:
    git:
        plugin: make
        source: .
        stage-packages:
            - curl
            - jq
            - libcurl4-openssl-dev
            - wget
        build-packages:
            - asciidoc
            - build-essential
            - curl
            - cvs
            - cvsps
            - docbook-xsl
            - gettext
            - libcurl4-openssl-dev
            - libdbd-sqlite3-perl
            - libsvn-perl
            - libyaml-perl
            - subversion
            - xmlto
            - wget
            - zlib1g-dev
        prime:
            - bin/
            - meta/hooks
            - usr/
    py:
        plugin: python
        python-packages:
            - urlparse2
            - launchpadlib
