#!/bin/bash
set -x

SNAP_UT=$1
CHANNEL=$2

#print the snap version
version=$(snap info "$SNAP_UT" | grep "${CHANNEL}:" | awk '{print $2}')
version="${version//16-/}"
version=$(echo "$version" | cut -f1 -d "~")

echo "$version"
