#!/bin/bash	
set -x

VERSION=$1

GITHUB_URL=https://github.com/snapcore/snapd.git

if git ls-remote --tags "$GITHUB_URL" "$VERSION" | grep -q "$VERSION"; then
    echo "$VERSION"
elif git ls-remote --heads "$GITHUB_URL" "release/$VERSION" | grep -q "$VERSION"; then
    echo "release/$VERSION"
elif echo "$VERSION" | grep -q '+git'; then
	echo "$VERSION" | sed 's/\+git.*//'
else
    echo "branch not found"
    exit 1
fi