#!/bin/bash

sudo cp snapd-testing/images/image-generator.service /etc/systemd/system/
sudo cp snapd-testing/images/image-generator.timer /etc/systemd/system/
sudo systemctl daemon-reload

sudo systemctl enable image-generator.timer image-generator.service
sudo systemctl start image-generator.timer
