#!/usr/bin/env python3

import argparse
import glob
import json
import logging
import os
import pathlib
import psutil
import requests
import shutil
import subprocess
import sys
import time
import urllib.request

S3_BUCKET_NAME = 'gs://snapd-spread-tests/images'
S3_PUBLIC_URL = 'https://storage.googleapis.com/snapd-spread-tests/images'
SUPPORTED_PLATFORMS = ['dragonboard','pc-amd64','pc-i386','pi4','pi3','pi2']
SUPPORTED_CHANNELS = ['edge', 'beta', 'candidate', 'stable']
SUPPORTED_VERSIONS = [16, 18, 20, 22]

IMAGE_EXT = '.img'
COMPRESSION_EXT = '.img.xz'
SEED_MANIFEST_FILE = 'seed.manifest'
IMAGE_SETS_FILE = 'image_sets.json'
IMAGES_TAG = 'images'

PROXY_PROTOCOL = 'http'
PROXY_HOST = 'squid.internal'
PROXY_PORT = '3128'


"""
This represents an architecture used for images and snaps
"""
class Architecture:

    PLATFORM_ARCH_MAP = {
        'pi2': 'armhf',
        'pi3': 'armhf',
        'pi4': 'arm64',
        'dragonboard': 'arm64',
        'pc-i386': 'i386',
        'pc-amd64': 'amd64'
    }

    @staticmethod
    def from_platform(platform):
        arch = Architecture.PLATFORM_ARCH_MAP.get(platform)
        if not arch:
            raise ValueError('Architecture not supported: {}'.format(arch))
        return arch


"""
This represents a snap with a name and channel from which provides
"""
class Snap:
 
    def __init__(self, definition, default_channel=None):

        self.name = definition.get('name')
        self.channel = definition.get('channel', default_channel)

        if not self.name:
            raise ValueError('snap name not defined: {}'.format(definition))

    def __repr__(self):
        return str(self.__dict__())

    def __dict__(self):
        return {'name': self.name, 'channel': self.channel}

    def __eq__(self, other):
        return self.name == other.name and self.channel == other.channel

    def __hash__(self):
        return hash((self.name, self.channel))

    @staticmethod
    def check_name_and_revision(name, revision):
        valid = True
        try:
            val = int(revision)
        except ValueError:
            valid = False
            logging.error('Revision value is not integer: {}'.format(revision))

        if not revision:
            valid = False
            logging.error('Revision not valid: {}'.format(revision))

        if not name:
            valid = False
            logging.error('Name not valid: {}'.format(name))

        return valid

    def find_revision(self, arch):
        logging.info('Requesting revision for snap: {}, channel: {} and arch: {}'.format(self.name, self.channel, arch))
        response = requests.get('https://search.apps.ubuntu.com/api/v1/snaps/details/{}?channel={}'.format(self.name, self.channel), 
            headers={'X-Ubuntu-Series': '16', 'X-Ubuntu-Architecture': '{}'.format(arch)}, timeout=30)

        if not response.ok:
            logging.error('Failed to get snap revision with status code: {}, raeson: {}'.format(response.status_code, response.reason))
            logging.error('Response details: {}'.format(response.text))
            raise RuntimeError('Error requesting the snap revision: {}'.format(response.text))

        revision = response.json().get('revision')
        if Snap.check_name_and_revision(self.name, revision):
            return int(revision)

        raise RuntimeError('Invalid revision: {} for snap: {}'.format(revision, self.name))


"""
This a snap with a revision
"""
class SnapVersion(Snap):
    def __init__(self, definition, default_channel=None):
        Snap.__init__(definition, default_channel)
   
        if not 'revision' in definition.keys():
            raise ValueError('snap revision not defined: {}'.format(definition))
        else:
            self.revision = definition['revision']

    def __repr__(self):        
        return str(self.__dict__())

    def __dict__(self):
        return {
            'name': self.name, 
            'channel': self.channel, 
            'revision': self.revision}

    def __eq__(self, other):
        return self.name == other.name and self.channel == other.channel and self.revision == other.revision

    def __hash__(self):
        return hash((self.name, self.channel, self.revision))


"""
This represents a trigger with is used to create a new image if needed
"""
class Trigger:
 
    def __init__(self, definition):
        self.snap = Snap(definition.get('snap'))

    def __repr__(self):
        return str(self.__dict__())

    def __dict__(self):
        return {'snap': self.snap.__dict__()}

    def __eq__(self, other):
        return self.snap.equals(other.snap)

"""
This represents a set of images with similar caracteristics but intended for 
different platforms. 
"""
class ImageSet:
    def __init__(self, definition):
        self.images = []

        platforms = definition.get('platforms')
        if not platforms:
            raise RuntimeError('Platforms not defined for image set')

        for platform in platforms:
            self.images.append(Image(definition, platform))

    def __repr__(self):
        return str(self.images)

    def __eq__(self, other):
        return set(self.images) == set(other.images)

    def get_images(self):
        return self.images


"""
Generates a list of images base of the image sets defined
This file contains the information needed to generate the images and publish them
"""
class ImageSetManager:

    def __init__(self, images_sets):
        self.images_sets = []
        for image_set_definition in images_sets:
            self.images_sets.append(ImageSet(image_set_definition))

    def get_all_images(self):
        all_images = []
        for images_set in self.images_sets:
            all_images.extend(images_set.get_images())

        return all_images


"""
This class represents a manifest which contains the snaps and revisions for an image
"""
class ImageManifest:
    def __init__(self, manifest_path=None, manifest_url=None, definition=None):
        self.manifest = {}

        if manifest_path:
            self._load_from_path(manifest_path)
            return

        if manifest_url:
            self._load_from_url(manifest_url)
            return

        if definition:
           self._load_from_definition(definition)
           return

    def __repr__(self):
        return str(self.__dict__())

    def __dict__(self):
        return self.manifest

    def __eq__(self, other):
        shared_items = [
            key for key in self.get_snap_names() if
            key in other.get_snap_names() and 
            self.manifest.get(key) == other.get(key)]

        return len(self.get_snap_names()) == len(shared_items) and len(self.get_snap_names()) == len(other.get_snap_names())

    def _load_from_definition(self, definition):
        self.manifest = definition

    def _load_manifest_part(self, line):
        parts = line.split(' ')
        if not len(parts) == 2:
            logging.warning('Manifest incorrect line: {}'.format(parts))
        else:
            snap = parts[0].strip()
            revision = parts[1].strip()
            if Snap.check_name_and_revision(snap, revision):
                self.manifest.update({snap: revision})
            else:
                logging.warning('Manifest incorrect snap: {} and revision: {}'.format(snap, revision))

    def _load_from_url(self, manifest_url):
        try:
            proxy_host = '{}://{}:{}'.format(PROXY_PROTOCOL, PROXY_HOST, PROXY_PORT)
            proxy_support = urllib.request.ProxyHandler({"http": proxy_host, "https": proxy_host})
            opener = urllib.request.build_opener(proxy_support)
            urllib.request.install_opener(opener)
            file = urllib.request.urlopen(manifest_url)
        except HTTPError as err:
            if err.code == 404:
                logging.warning('The manifest url does not exist')
                raise RuntimeError('The manifest url does not exist')
            else:
                raise 

        for line in file:
            self._load_manifest_part(line.decode('utf-8'))

    def _load_from_path(self, manifest_path):
        if not os.path.exists(manifest_path):
            raise ValueError('No manifest in path: {}'.format(manifest_path))

        with open(manifest_path, 'r') as file:
            for line in file.readlines():
                self._load_manifest_part(line)
                

    def get_snap_revision(self, snap):
        revision = self.manifest.get(snap.name)
        try:
            return int(revision)
        except ValueError:
            logging.error('Revision value is not integer: {}'.format(revision))
            return

    def get_snap_names(self):
        return self.manifest.keys()

    def empty(self):
        return len(self.get_snap_names()) == 0


"""
This class represents an image with all its attributes and the including the triggers
which are used to update
"""
class Image:
    IMAGE_FILE = 'image.json'

    def __init__(self, definition, default_platform=None):
        self.version = definition.get('version')
        self.channel = definition.get('channel')
        self.manifest = ImageManifest(definition=definition.get('manifest'))
        self.platform = definition.get('platform', default_platform)

        if not self.channel in SUPPORTED_CHANNELS:
            raise ValueError('channel: {} not supported. Supported channels: {}'.format(self.channel, SUPPORTED_CHANNELS))

        if not self.version in SUPPORTED_VERSIONS:
            raise ValueError('version: {} not supported. Supported versions: {}'.format(self.channel, SUPPORTED_VERSIONS))

        if not self.platform:
            raise ValueError('platform list empty')
    
        if not self.platform in SUPPORTED_PLATFORMS:
            raise ValueError('platform: {} not supported. Supported platform: {}'.format(self.platform, SUPPORTED_PLATFORMS))

        self.triggers = []
        for trigger in definition.get('triggers'):
            self.triggers.append(Trigger(trigger))

        self.snaps = []
        for snap in definition.get('snaps'):
            self.snaps.append(Snap(snap))

        self.output_dir = self._get_output_dir()
        self.remote_manifest = None

    def __repr__(self):        
        return str(self.__dict__())

    def __dict__(self):        
        snaps_dict = []
        for snap in self.snaps:
            snaps_dict.append(snap.__dict__())            

        triggers_dict = []
        for trigger in self.triggers:
            triggers_dict.append(trigger.__dict__())  

        manifest_dict = self.manifest.__dict__()

        return {
            'version': self.version, 
            'channel': self.channel, 
            'manifest': manifest_dict, 
            'snaps': snaps_dict, 
            'triggers': triggers_dict,
            'platform': self.platform}

    def __eq__(self, other):
        return self.version == other.version and \
            self.channel == other.channel and \
            self.manifest == other.manifest and \
            self.platform == other.platform and \
            set(self.snaps) == set(other.snaps)

    def get_image_name(self):
        name = '{}-{}-{}'.format(self.platform, self.version, self.channel.replace('/', '~'))
        for snap in self.snaps:
            name = '{}-{}_{}'.format(name, snap.name, snap.channel.replace('/', '~'))
        return name

    def _get_output_dir(self):
        output_dir = os.path.join('output', self.get_image_name())        

        logging.info('Output dir used: {}'.format(output_dir))
        return output_dir        

    def _find_in_output_dir(self):
        images = glob.glob('{}/*{}'.format(self.output_dir, IMAGE_EXT))
        images.extend(glob.glob('{}/*{}'.format(self.output_dir, COMPRESSION_EXT)))
        if len(images) == 1:
            return images[0]

    "This method is similar to __eq__ but it doesn't match the manifest"

    def match(self, other):
        return self.version == other.version and \
            self.channel == other.channel and \
            self.platform == other.platform and \
            ( self.manifest == other.manifest or self.manifest.empty or other.manifest.empty ) and \
            set(self.snaps) == set(other.snaps)

    def is_image_dir_created(self):
        return os.path.isdir(self.output_dir)        

    def get_image_already_created(self):
        if os.path.isdir(self.output_dir):
            return self._find_in_output_dir()

    def get_manifest_url(self):
        return '{}/{}/{}'.format(S3_PUBLIC_URL, self.get_image_name(), 'seed.manifest')

    def get_remote_revision(self, snap):
        if not self.remote_manifest:
            manifest_url = self.get_manifest_url()
            self.remote_manifest = ImageManifest(manifest_url=manifest_url)

        return self.remote_manifest.get_snap_revision(snap)

    def read_manifest(self):
        manifest_dict = {}
        manifest_path = os.path.join(self.output_dir, SEED_MANIFEST_FILE)
        
        if not os.path.exists(manifest_path):
            raise RuntimeError('Manifest file does not exist: {}'.format(manifest_path))

        self.manifest = ImageManifest(manifest_path=manifest_path)

    def save_image(self):
        image_file = os.path.join(self.output_dir, self.IMAGE_FILE)

        if os.path.exists(image_file):
            return

        logging.info('Saving to image info: {}'.format(image_file))
        with open(image_file, 'w+') as json_file:
            json.dump(self.__dict__(), json_file)


    def is_new_image_needed(self):
        logging.info('Checking if new image is needed')

        for trigger in self.triggers:
            trigger_snap = trigger.snap

            try:
                snap_revision_store = trigger_snap.find_revision(Architecture.from_platform(self.platform))
                logging.info('Revision for snap: {}, obtained from store: {}'.format(trigger_snap, snap_revision_store))
            except Exception:
                logging.error('Failed to get snap revision from store for snap {}'.format(trigger_snap))
                return True

            try:
                snap_revision_remote = self.get_remote_revision(trigger_snap)
                logging.info('Revision for snap: {}, obtained from gce storage: {}'.format(trigger_snap, snap_revision_remote))
            except Exception:
                logging.warning('Snap revision could not be found in remote manifest')
                return True

            if snap_revision_store > snap_revision_remote:
                logging.info('Revision for snap {} on store is higher {} than in manifest {}'.format(
                    trigger_snap, snap_revision_store, snap_revision_remote))
                return True

        logging.info('New image is not needed')
        return False


"""
This class Creates, compress and synchronize the ubuntu core images
"""
class ImageProcessor:
    def __init__(self, image):
        self.image = image

    def _get_snap_list(self):
        snap_list = []
        for snap in self.image.snaps:
            snap_param = '{}={}'.format(snap.name, snap.channel)
            snap_list.append(snap_param)

        return sorted(snap_list)

    def get_image_options(self):
        if self.image.version >= 20:
            return '--image-size 8G'
        if self.image.platform.startswith('pc'):
            return '--image-size 3G'
        return ''

    def get_snap_options(self):
        snaps_option = ''
        for snap in self._get_snap_list():
            snaps_option = '{} --snap {}'.format(snaps_option, snap)
        return snaps_option

    def create_image(self):
        # Clean the output dir
        if os.path.isdir(self.image.output_dir):
            logging.info('Regenerating output dir: {}'.format(self.image.output_dir))
            shutil.rmtree(self.image.output_dir)
            os.mkdir(self.image.output_dir)

        # Create the image using ubuntu-image tool
        image_option = self.get_image_options()
        snaps_option = self.get_snap_options()
        
        line = "/snap/bin/ubuntu-image snap {} {} -c {} -O {} ./models/{}-{}.model".format(
            image_option, snaps_option, 
            self.image.channel, self.image.output_dir, 
            self.image.platform, self.image.version)

        logging.info('Running command line: {}'.format(line))
        subprocess.call(line, shell=True, timeout=600)

        self.image.read_manifest()
        self.image.save_image()

    def _check_trigger(self, trigger_snap):
        logging.info('Checking revisions for snap {}'.format(trigger_snap.name))

        # Get store revision
        try:
            store_rev = trigger_snap.find_revision(Architecture.from_platform(self.image.platform))
        except RuntimeError:
            logging.warning("Revision from the store couldn't be retrieved, skiping checks")
            return False

        # Get remote revision
        try:
            remote_rev = ImageManifest(manifest_url=self.image.get_manifest_url()).get_snap_revision(trigger_snap)
        except RuntimeError:
            logging.warning("Revision from the remote manifes couldn't be retrieved, skiping checks for this rev")
            return True

        # Get image revision
        image_rev = self.image.manifest.get_snap_revision(trigger_snap)

        if not image_rev == store_rev:
            logging.info("Revision from the image manifest '{}' is different of the the revision from the store '{}'".format(image_rev, store_rev))
            return False

        if not image_rev > remote_rev:
            logging.info("Revision from the image '{}' is not higher than revision from remote manifest'{}'".format(image_rev, remote_rev))
            return False                

        return True


    def check_image(self):
        if not os.path.isdir(self.image.output_dir):
            raise RuntimeError('Output dir for the image to check does not exist: {}'.format(self.image.output_dir))

        manifest = self.image.manifest
        for trigger in self.image.triggers:
            if self._check_trigger(trigger.snap):
                logging.info("Check for trigger snap '{}' passed".format(trigger.snap.name))
                return True
            
        logging.error("Check for triggers failed")
        return False


    def delete_image(self):
        # Clean the output dir
        if not os.path.isdir(self.image.output_dir):
            raise RuntimeError('Output dir does not exist')

        logging.info('Removing image: {}'.format(self.image.output_dir))
        try:
            shutil.rmtree(self.image.output_dir)
        except OSError as e:
            logging.error('Failed to delete image dir {}'.format(self.image.output_dir))


    def sync_image(self, proxy_host, proxy_port):
        dirname = os.path.basename(self.image.output_dir)
        proxy = os.environ.get('HTTPS_PROXY','')
        if proxy_host and proxy_port:
            gsutil_config = '-o GSUtil:parallel_composite_upload_threshold=2000M -o Boto:proxy={} -o Boto:proxy_port={}'.format(proxy_host, proxy_port)
        else:
            gsutil_config = '-o GSUtil:parallel_composite_upload_threshold=2000M'

        line_delete = 'gsutil {} rm -r -f {}/{}'.format(gsutil_config, S3_BUCKET_NAME, dirname)
        logging.info('Running command line: {}'.format(line_delete))
        subprocess.call(line_delete, shell=True, timeout=600)

        line_cp = 'gsutil {} cp -r {} {}'.format(gsutil_config, self.image.output_dir, S3_BUCKET_NAME)
        logging.info('Running command line: {}'.format(line_cp))
        subprocess.call(line_cp, shell=True, timeout=600)

    def compress_image(self):
        image_path = self.image.get_image_already_created()

        if image_path.endswith(COMPRESSION_EXT):
            logging.warning('Image {} already compressed'.format(image_path))
            return

        line = 'xz {}'.format(image_path)
        logging.info('Running command line: {}'.format(line))
        subprocess.call(line, shell=True, timeout=900)

        if os.path.exists(image_path):
            raise RuntimeError('Image file still exists after compress it')

        if not os.path.exists('{}.xz'.format(image_path)):
            raise RuntimeError('Image file with compression has not been created')

    def process_image(self, proxy_host="", proxy_port=""):
        self.create_image()

        checked = self.check_image()
        if checked:
            self.compress_image()
            self.sync_image(proxy_host, proxy_port)

        self.delete_image()

        if checked:
            return self.image

        return None


"""
This class creates a list of images
"""
class ImagesManager:
    def __init__(self):
        pass

    def create_images(self, images):
        created_images = []
        for image in images:
            logging.info('Starting with image: {}'.format(image))

            if not image.is_new_image_needed():
                logging.info('No image needed for image: {}'.format(image))
                continue

            processor = ImageProcessor(image)
            try:
                image_new = processor.process_image(proxy_host=PROXY_HOST, proxy_port=PROXY_PORT)
            except Exception:
                logging.error('Image {} could not be processed correctly'.format(image))
                continue

            if image_new:
                logging.info('Image {} processed successfully'.format(image_new))
                created_images.append(image_new)
            else:
                logging.error('Image {} could not be processed correctly'.format(image))

        return created_images


class ImageFiles:
    
    @staticmethod
    def read_images_set():
        return ImageFiles._read_sets(IMAGES_TAG)

    @staticmethod
    def _read_sets(tag):
        if not os.path.exists(IMAGE_SETS_FILE):
            raise RuntimeError('Sets file not found: {}'.format(IMAGE_SETS_FILE))

        with open(IMAGE_SETS_FILE) as json_file:  
            data = json.load(json_file)
            
            if not tag in data.keys():
                raise RuntimeError('Tag {} not found on file: {}'.format(tag, IMAGE_SETS_FILE))

            return data.get(tag)


class ProcessManager:

    @staticmethod
    def is_image_generator_already_running():
        count = 0
        for proc in psutil.process_iter():
            try:
                pinfo = proc.as_dict(attrs=['pid', 'name', 'cmdline'])
                if 'python3' == pinfo.get('name'):
                    for line in pinfo.get('cmdline'):
                        if line.endswith('/image-generator'):
                            count = count + 1
            except psutil.NoSuchProcess:
                return False

        return count > 1


def process_images():
    images_sets_manager = ImageSetManager(ImageFiles.read_images_set())
    images_manager = ImagesManager()

    # Create the images
    all_images = images_sets_manager.get_all_images()
    used_images = images_manager.create_images(all_images)

    if used_images:
        logging.info("Images created:")
        logging.info(used_images)
    else:
        logging.info("No images created")
    

def process_image_cli(version, channel, platform, snaps, publish, proxy_host, proxy_port):
    image_def = {}
    image_def['version'] = version
    image_def['channel'] = channel
    image_def['platform'] = platform
    image_def['manifest'] = {}

    # Process the snaps for the image
    snaps_def = []
    for snap in snaps:
        snap_def = {}
        snap_parts = snap.split('=')
        if not len(snap_parts) == 2:
            raise ValueError('Incorrect format received for snap (NAME=CHANNEL). Value not supported: {}'.format(snap))
        snap_def['name'] = snap_parts[0]
        snap_def['channel'] = snap_parts[1]
        snaps_def.append(snap_def)

    image_def['snaps'] = snaps_def
    image_def['triggers'] = []

    image = Image(image_def)
    processor = ImageProcessor(image)
    try:
        if publish:
            image_new = processor.process_image(proxy_host, proxy_port)
        else:
            image_new = processor.create_image()
    except Exception:
        logging.error('Image {} could not be processed correctly'.format(image))
        sys.exit(1)


def check_parameters(ns):
    return ns.version and ns.channel and ns.platform and ns.snap


def snap_channel(s):
    if not len(s.split('=')) == 2:
        raise argparse.ArgumentTypeError("snap variables expected format is 'SNAP=CHANNEL' got '{}'".format(s))
    return s


def _make_parser():
    parser = argparse.ArgumentParser(
            description="""
Generate an ubuntu core image using the desired parameters
"""
    )
    parser.add_argument(
        "-v",
        "--version",
        metavar='VERSION',
        type=int,
        choices=SUPPORTED_VERSIONS,
        help="version used to build the image",
    )
    parser.add_argument(
        "-c",
        "--channel",
        metavar='CHANNEL',
        type=str,
        choices=SUPPORTED_CHANNELS,
        help="channel used to build the image",
    )
    parser.add_argument(
        "-p",
        "--platform",
        metavar='PLATFORM',
        type=str,
        choices=SUPPORTED_PLATFORMS,
        help="platform used to build the image",
    )
    parser.add_argument(
        "--snap",
        type=snap_channel,
        metavar='SNAP=CHANNEL',
        action='append',
        default=[],
        help="Snap to be used to build the image",
    )
    parser.add_argument(
        "--publish",
        action="store_true",
        help="Indicate if the image has to be published to gce bucket",
    )
    parser.add_argument(
        "--proxy-host",
        metavar='PROXY_HOST',
        default='',
        type=str,
        help="proxy url used to connect to gce bucket",
    )
    parser.add_argument(
        "--proxy-port",
        metavar='PROXY_PORT',
        default='',
        type=str,
        help="proxy port used to connect to gce bucket",
    )

    return parser


if __name__ == "__main__":
    logging.basicConfig(format='%(levelname)s - %(message)s', level=logging.INFO)

    if ProcessManager.is_image_generator_already_running():
        logging.warning('Image generator already being executed, skipping...')
        sys.exit()
    
    parser = _make_parser()
    ns = parser.parse_args()

    # When the parser doesn't receive any command, the configuration file is used
    if check_parameters(ns):
        if not ns.version or not ns.channel or not ns.platform:
            logging.error('Version, Channel and platform are needed as parameter to manually trigger an image build')
            parser.print_usage()
            parser.exit(0)
        process_image_cli(ns.version, ns.channel, ns.platform, ns.snap, ns.publish, ns.proxy_host, ns.proxy_port)
    else:
        process_images()
