#!/bin/bash

cd "$SNAP_DATA"

if [ ! -f "spread.yaml" ]; then
    echo "File $SNAP_DATA/spread.yaml does not exist, using the default one"
    cp -f "$SNAP/spread.yaml" "spread.yaml"
    cp -rf "$SNAP/fakesuite" "fakesuite"
fi
echo "Using spread.yaml: $SNAP_DATA/spread.yaml"

if [ -f "sa.json" ]; then
    SPREAD_GOOGLE_KEY="$SNAP_DATA/sa.json"
elif [ -f "application_default_credentials.json" ]; then
    SPREAD_GOOGLE_KEY="$SNAP_DATA/application_default_credentials.json"
else
    echo "Credentials not found, exiting..."
    exit
fi
echo "Using service account: $SPREAD_GOOGLE_KEY"

if [ ! -f "spread" ]; then
    echo "Getting spread"
    curl -s -O https://storage.googleapis.com/snapd-spread-tests/spread/spread-amd64.tar.gz && tar xzvf spread-amd64.tar.gz && rm -f spread-amd64.tar.gz
fi

export SPREAD_GOOGLE_KEY

echo "Cleaning virtual machines in all the backends included in the spread.yaml"
./spread -gc

echo "Clean up finished"



