#!/bin/bash

if [ ! -f "$SNAP_DATA/spread.yaml" ]; then
    echo "File $SNAP_DATA/spread.yaml does not exist, exiting..."
    exit
fi
echo "Using spread.yaml: $SNAP_DATA/spread.yaml"

if [ -f "$SNAP_DATA/sa.json" ]; then
    SPREAD_GOOGLE_KEY="$SNAP_DATA/sa.json"
elif [ -f "$SNAP_DATA/application_default_credentials.json" ]; then
    SPREAD_GOOGLE_KEY="$SNAP_DATA/application_default_credentials.json"
else
    echo "Credentials not found, exiting..."
    exit
fi
echo "Using service account: $SPREAD_GOOGLE_KEY"

if [ ! -f "$SNAP_DATA/spread" ]; then
    echo "Getting spread"
    cd "$SNAP_DATA" && curl -s -O https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz && tar xzvf spread-amd64.tar.gz
fi

export SPREAD_GOOGLE_KEY
cd "$SNAP_DATA" && "$SNAP_DATA/spread" -gc google
