#!/bin/bash

ARCH=${ARCH:-"amd64"}

PROJECT=${PROJECT:-"snapd"}
PROJECT_URL=${PROJECT_URL:-"https://github.com/snapcore/snapd.git"}

CHANNEL=${CHANNEL:-"stable"}

SPREAD_TESTS=${SPREAD_TESTS:-"google-sru"}
SPREAD_ENV=${SPREAD_ENV:-"SPREAD_MODIFY_CORE_SNAP_FOR_REEXEC=0 SPREAD_TRUST_TEST_KEYS=false SPREAD_SNAP_REEXEC=0 SPREAD_CORE_CHANNEL=stable SPREAD_SRU_VALIDATION=1"}

TESTS_BACKEND=google
TESTS_DEVICE=sru