#!/bin/bash

set -x

SNAP_UT=$1
VERSION_UT=$2
REVISION_UT=$3
CHANNEL_UT=$4
CONFIG=$5
BOARD_UT=$6
ARCH_UT=$7
SPREAD_LOG=$8
SUMMARY_LOG=$9
ATTACH_LOG=${10}

# Get current dir
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Exit in case important data is not defined
if [ ! -s "$SPREAD_LOG" ]; then
    echo "Spread log does not exist or is empty: $SPREAD_LOG"
    exit 1
fi

if [ -z "$VERSION_UT" ] || [ -z "$REVISION_UT" ]; then
    echo "Version $VERSION_UT or revision $REVISION_UT not detected"
    exit 1
fi

# Generate the summary of the test execution
"${DIR}"/log-analyzer "$SPREAD_LOG" -pr all | tee "$SUMMARY_LOG"

# Generate the errors log of the test execution
"${DIR}"/log-analyzer "$SPREAD_LOG" -pd error-debug -pr all | tee "$ERRORS_LOG"

# Create card in trello
"${DIR}"/trello-board-updater-ng create -s "$SNAP_UT" -v "$VERSION_UT" -r "$REVISION_UT" --channel "$TARGET_CHANNEL" --config "${DIR}/data/${CONFIG}"

# Calculate the results to upload to trello
# If "Successful tasks:" is found it means the spread execution was done
if grep -q "Successful tasks:" "$SPREAD_LOG"; then
    RESULT="--passed"
fi

# If "error: unsuccessful run" is found it means the spread execution failed
if grep -q "error: unsuccessful run" "$SPREAD_LOG"; then
    RESULT=""
fi

# Upload the results to trello
if [ -z "$RESULT" ]; then
	"${DIR}"/trello-board-updater-ng add-result -s "$SNAP_UT" -v "$VERSION_UT" -r "$REVISION_UT" -n "$BOARD_UT" -a "$ARCH_UT" --summary "$SUMMARY_LOG"
else
	"${DIR}"/trello-board-updater-ng add-result -s "$SNAP_UT" -v "$VERSION_UT" -r "$REVISION_UT" -n "$BOARD_UT" -a "$ARCH_UT" --summary "$SUMMARY_LOG" "$RESULT"
fi
"${DIR}"/trello-board-updater-ng complete -s "$SNAP_UT" -v "$VERSION_UT" -r "$REVISION_UT" --config "${DIR}/data/${CONFIG}"

# Generate the reduced log and upload to trello as an attachment
"${DIR}"/log-analyzer "$SPREAD_LOG" -c 200 --store-setup | tee "$ATTACH_LOG"
attachment="${SNAP_UT}_${VERSION_UT}_${REVISION_UT}_${BOARD_UT}_${ARCH_UT}.log"
if [ -s "$ATTACH_LOG" ]; then
    "${DIR}"/trello-board-updater-ng attach -s "$SNAP_UT" -v "$VERSION_UT" -r "$REVISION_UT" --name "$attachment" --file "$ATTACH_LOG"
else
	echo "Attachment file is empty so it is not uploaded"
fi
