name: Print time every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  print-time:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: date